name: My action
description: Testing a custom action

inputs:
  name:
    description: "The name to print"
    required: true
    default: "mundo"

runs:
  using: "composite"

  steps:
    - name: Hola mundo
      run: echo "Hola ${{ inputs.name }}"
      shell: bash