name: use actions

# eventos: trigers que indican que el workflow se debe ejecutar
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout dir
      uses: actions/checkout@v2

    - name: ls
      run: ls -a

    - name: custom action
      uses: ./.github/actions/new-action
      with:
        name: "sebasjp"