name: workflow prueba

# eventos: trigers que indican que el workflow se debe ejecutar
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Hola Mundo
      run: echo "Hola Mundo"
    - name: touch file
      run: touch hola.txt
    - name: set text
      run: echo "Hola Mundo" >> hola.txt
    - name: Read file
      run: cat hola.txt
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: Checkout
      run: actions/checkout@v4.1.7  # ejecucion de una agrupacion de steps
    - name: LS
      run: ls -al