name: variables de entorno

# eventos: trigers que indican que el workflow se debe ejecutar
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env: # variables de entorno a nivel job
      VAR_JOB: "var entorno nivel job"

    steps:
      - name: print var job
        run: echo "VAR_JOB=$VAR_JOB"

      - name: print var step 
        env: # variable a nivel step
          VAR_STEP: "var entorno nivel step"
        run: echo "VAR_STEP=$VAR_STEP"

      - name: print var from github
        run: echo "VAR_ENV_REPO=${{ vars.VAR_ENV_REPO }}" # traer variables a nivel repo (desde github aplica para todos los workflows)

      - name: print secrets from github
        run: echo "SECRET_TEST=${{ secrets.SECRET_TEST }}" # traer secrets a nivel repo (desde github aplica para todos los workflows)
